name: 🚀 Build and Deploy Pycade Bomber to Web

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '**/*.md'
      - 'docs/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📚 Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pygbag pytest pytest-mock flake8

      - name: 🧪 Verify Template File Presence
        run: |
          echo "🔍 Checking for custom index.html.template..."
          test -f web/index.html.template && echo "✅ Template found!" || echo "❌ Template missing!"

      - name: 🏗️ Build Web Version with Pygbag
        timeout-minutes: 30
        run: |
          echo "🔧 Building web version with pygbag..."
          pygbag --build --archive .
          echo "✅ Pygbag build completed."

      - name: 🔎 Verify Build Output
        run: |
          echo "📁 Checking contents of build/web..."
          ls -R build/web
          if [ -d "build/web" ] && [ "$(ls -A build/web)" ]; then
            echo "✅ build/web is valid and not empty."
          else
            echo "❌ Error: build/web is empty or missing!"
            exit 1
          fi

      - name: 📤 Upload GitHub Pages Artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: 🚀 Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
