name: 🧪 Run Pygame Tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '**/*.md'
      - 'docs/**'

jobs:
  Run-Pygame-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📚 Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pygbag pytest pytest-mock flake8

      - name: 🧹 Lint code with Flake8
        run: |
          echo "🔎 Running flake8 for style check..."
          flake8 .
          echo "✅ Flake8 completed."

      - name: 🧪 Run tests with Pytest
        run: |
          echo "🚀 Launching test suite..."
          pytest
